# Generated by Django 5.1.2 on 2024-10-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_authormodel_created_at_authormodel_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='image',
        ),
    ]
